name: Download ARM RPM Packages for Kylin

# 允许我们手动点击按钮来触发这个任务
on:
  workflow_dispatch:

jobs:
  build-and-package:
    # 使用 GitHub 官方提供的、配置完整的 Ubuntu 最新环境
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 输出提示信息
      - name: Starting package download
        run: echo "Preparing to download iperf3 and redis for aarch64..."

      # 步骤 2: 创建用于存放包的目录
      - name: Create package directory
        run: mkdir kylin_arm_packages

      # 步骤 3: 运行 Docker 命令下载软件包 (核心步骤)
      - name: Run Docker to download packages
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}/kylin_arm_packages:/packages \
            rockylinux:8 \
            bash -c "dnf install -y dnf-utils && cd /packages && yumdownloader --resolve --archlist=aarch64 iperf3 redis"

      # 步骤 4: 将下载好的文件夹打包上传
      - name: Upload packages as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: kylin-arm-packages-rpm
          path: kylin_arm_packages/
