name: Download ARM RPM Packages for Kylin

# 允许我们手动点击按钮来触发这个任务
on:
  workflow_dispatch:

jobs:
  build-and-package:
    # 使用 GitHub 官方提供的、配置完整的 Ubuntu 最新环境
    runs-on: ubuntu-latest

    steps:
      # ====================================================================
      # 关键的新增步骤：安装并配置 QEMU 模拟器
      # 这样 runner 才能运行非 x86 架构的 Docker 镜像
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # ====================================================================

      # 步骤 2: 输出提示信息
      - name: Starting package download
        run: echo "QEMU is set up. Preparing to download iperf3 and redis for aarch64..."

      # 步骤 3: 创建用于存放包的目录
      - name: Create package directory
        run: mkdir kylin_arm_packages

      # 步骤 4: 运行 Docker 命令下载软件包 (现在可以正常工作了)
      - name: Run Docker to download packages
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}/kylin_arm_packages:/packages \
            rockylinux:8 \
            bash -c "dnf install -y dnf-utils && cd /packages && yumdownloader --resolve --archlist=aarch64 iperf3 redis"

      # 步骤 5: 将下载好的文件夹打包上传
      - name: Upload packages as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: kylin-arm-packages-rpm
          path: kylin_arm_packages/
