name: Download x86_64 RPM Packages for NeoKylin V7

on:
  workflow_dispatch:

jobs:
  build-x86-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Starting package download for x86_64
        run: echo "Preparing to download iperf3 and redis for CentOS 7 (x86_64)..."

      - name: Create package directory
        run: mkdir neokylin_x86_packages

      - name: Run Docker to download packages using CentOS 7
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/neokylin_x86_packages:/packages \
            centos:7 \
            bash -c " \
              sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo && \
              sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo && \
              yum install -y yum-utils && \
              cd /packages && \
              yumdownloader --resolve iperf3 redis \
            "

      - name: Upload packages as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: neokylin-x86-packages-rpm
          path: neokylin_x86_packages/
